spring.application.name=kourts-api
server.port=8081

## Instrução para criar o BDA se ele não existir
spring.datasource.url=jdbc:mysql://localhost:3306/db_kourts?createDatabaseIfNotExist=true&serverTimezone=UTC
## Nome do usuario do banco
spring.datasource.username=root
## Senha do usuario no banco
spring.datasource.password=

## Comando que permite o Hibernate modelar o banco
spring.jpa.hibernate.ddl-auto=update

## Comando para mostrar as instruções SQL no console
spring.jpa.show-sql=true

## Teste de requisão de um computador externo
## server.address=0.0.0.0